VerzovaciSystem/VerzovaciSystem/Controllers/SelectionMaskController.cs
using System;
using System.Web.Mvc;
using VerzovaciSystem.Models;
using VerzovaciSystem.Models.Interfaces;

namespace VerzovaciSystem.Controllers
{
    public class SelectionMaskController : Controller
    {
        //Autofac
        private readonly ISelectionMaskViewModel selectionMaskViewModel;

        //Autofac
        public SelectionMaskController(ISelectionMaskViewModel iSelectionMaskViewModel)
        {
            selectionMaskViewModel = iSelectionMaskViewModel;
        }

        // zobrazení nabídky vyhledávací masky
        public ActionResult SelectionMask()
        {
            selectionMaskViewModel.GetSelectionMask();
            return View(selectionMaskViewModel);
        }

        // zobrazení výsledku hledání dle zadání ve vyhledávací masce
        [HttpPost]
        public ActionResult SelectionMask(SelectionMaskViewModel selectionMaskViewModel)
        {
            if (selectionMaskViewModel.SelectionMaskEntity.Id == null &&
                (selectionMaskViewModel.SelectionMaskEntity.CompanyTyp == null) &&
                (selectionMaskViewModel.SelectionMaskEntity.Company == null) &&
                (selectionMaskViewModel.SelectionMaskEntity.CompanyWithGroup == null) &&
                (selectionMaskViewModel.SelectionMaskEntity.Group == null) &&
                (selectionMaskViewModel.SelectionMaskEntity.VersionDateFrom == DateTime.MinValue) &&
                (selectionMaskViewModel.SelectionMaskEntity.VersionDateTo == DateTime.MinValue) &&
                (selectionMaskViewModel.SelectionMaskEntity.CreationDateFrom == DateTime.MinValue) &&
                (selectionMaskViewModel.SelectionMaskEntity.CreationDateTo == DateTime.MinValue) &&
                (selectionMaskViewModel.SelectionMaskEntity.SearchInDeleted == false) 
               ) 
                {
                TempData["result"] = "Nebylo vyplněno aspoň jedno pole nebo pole nebyla vyplněna správnými hodnotami";

                return RedirectToAction("SelectionMask");
                }

            selectionMaskViewModel.GetSelectedRecords(selectionMaskViewModel.SelectionMaskEntity);
            TempData["selectionMaskVersions"] = "Nalezené verze:";

            return View("SelectionMaskOutput",selectionMaskViewModel);
        }

        // pro odkaz v Layotu - dnešní verze a po startu aplikace
        public ActionResult GetTodayVersions()
        {
            selectionMaskViewModel.GetTodayVersions();
            TempData["todaysVersions"] = "Seznam dnešních verzí:";
            return View("SelectionMaskOutput", selectionMaskViewModel);
        }
    }
}

VerzovaciSystem/VerzovaciSystem/Controllers/VersionsController.cs
using System.Web.Mvc;
using System;
using VerzovaciSystem.Models;
using VerzovaciSystem.Models.Entities;
using System.Collections.Generic;
using VerzovaciSystem.Models.Interfaces;

namespace VerzovaciSystem.Controllers
{
    public class VersionsController : Controller
    {
        private readonly IVersionsViewModel versionsViewModel;

        public List<SelectListItem> Companies { get; private set; }

        public VersionsController(IVersionsViewModel iVersionsViewModel)
        {
            versionsViewModel = iVersionsViewModel;
        }

        // vrací jednu verzi z VERSION_LOG se všemi sloupci
        public ActionResult GetVersion(long idVersion)
        {
            versionsViewModel.GetVersion(idVersion);
            return View(versionsViewModel);
        }

        // vrací data z db VER_SQL_DATA kolonky
        public ActionResult GetSqlData(long idVersion)
        {
            versionsViewModel.GetSqlData(idVersion);
            return View(versionsViewModel);
        }

        // vrací data z db VER_SQL_DATA_CHECK kolonky
        public ActionResult GetSqlDataCheck(long idVersion)
        {
            versionsViewModel.GetSqlDataCheck(idVersion);
            return View(versionsViewModel);
        }
        // vrací verzi z VERSION_LOG k potvrzení odstranění
        public ActionResult GetVersionForDeletion(long idVersion)
        {
            versionsViewModel.GetVersion(idVersion);
            return View(versionsViewModel);
        }

        // zašle verzi k odstranění z VERSION_LOG
        public ActionResult DeleteVersion(long idVersion)
        {
            TempData["result"] = versionsViewModel.DeleteVersion(idVersion);
            return RedirectToAction("GetTodayVersions", "SelectionMask");
        }

        // vrací verzi z VERSION_LOG k provedení aktualizace
        public ActionResult ChangeVersion(long idVersion)
        {
            versionsViewModel.GetVersion(idVersion);
            versionsViewModel.Version.LogUser = $"{Environment.MachineName}/{Environment.UserName}";

            if (versionsViewModel.Version.LogFlagString == "A")
                versionsViewModel.Version.LogFlagBool = true;

            else
                versionsViewModel.Version.LogFlagBool = false;

            return View(versionsViewModel.Version);
        }

        // zašle verzi k aktualizaci v VERSION_LOG
        [HttpPost]
        public ActionResult ChangeVersion(VersionEntity versionToChange)
        {
            if (!ModelState.IsValid)
            {
                return View(versionToChange);
            }

            if (versionToChange.LogFlagBool)
                versionToChange.LogFlagString = "A";
            else
                versionToChange.LogFlagString = "N";

            TempData["result"] = versionsViewModel.ChangeVersion(versionToChange);
            return RedirectToAction("GetVersion", new { idVersion = versionToChange.Id });
        }

        // NOVÁ VERZE
        // zobrazí prázdný formulář pro zadání nové verze
        public ActionResult AddVersion()
        {
            versionsViewModel.GetTemplateVersionsAndCompanies();
            versionsViewModel.Version = new VersionEntity($"{Environment.MachineName}/{Environment.UserName}",
                                                          DateTime.Now,
                                                          DateTime.Now
                                                         );
            return View(versionsViewModel);
        }

        // zobrazí předvyplněný formulář z vybraného vzoru pro zadání nové verze
        [HttpPost]
        public ActionResult GetTemplateVersion(VersionsViewModel versionsViewModel)
        {
            if (versionsViewModel.TemplateVersionId == 0)
            {
                TempData["result"] = "Nebyl vybrán vzor";
                return RedirectToAction("AddVersion");
            }

            versionsViewModel.GetTemplateVersion(versionsViewModel.TemplateVersionId);
            versionsViewModel.GetTemplateVersionsAndCompanies();
            return View("AddVersion", versionsViewModel);
        }

        // zašle novou verzi z formuláře k uložení do db
        [HttpPost]
        public ActionResult AddVersion(VersionsViewModel versionsViewModel)
        {
            versionsViewModel.Version.LogDate = DateTime.Now;
            versionsViewModel.Version.Created = DateTime.Now;

            if (!ModelState.IsValid)
            {
                versionsViewModel.GetTemplateVersionsAndCompanies();
                return View(versionsViewModel);
            }

            if (versionsViewModel.Version.DeletedBool)
                versionsViewModel.Version.DeletedString = "A";
            else
                versionsViewModel.Version.DeletedString = "N";

            if (versionsViewModel.Version.LogFlagBool)
                versionsViewModel.Version.LogFlagString = "A";
            else
                versionsViewModel.Version.LogFlagString = "N";

            long versionId = 0;
            TempData["result"] = versionsViewModel.AddVersion(versionsViewModel.Version,ref versionId);
            return RedirectToAction("GetVersion", new { idVersion = versionId});
        }
    }
}

VerzovaciSystem/VerzovaciSystem/Controllers/VersionsFlagController.cs
using System.Web.Mvc;
using VerzovaciSystem.Models.Interfaces;

namespace VerzovaciSystem.Controllers
{
    public class VersionsFlagController : Controller
    {
        //Autofac
        private readonly IVersionsFlagViewModel versionsFlagViewModel;

        public VersionsFlagController(IVersionsFlagViewModel iVersionsFlagViewModel)
        {
            versionsFlagViewModel = iVersionsFlagViewModel;
        }

        // zobrazí události k požadovanému číslu verze z VERSION_LOG 
        public ActionResult GetFlagVersions(long versionLogId)
        {
            versionsFlagViewModel.GetEventsToVersion(versionLogId);

            return View(versionsFlagViewModel);
        }

        // zobrazí obsah log souboru k požadovanému číslu z VERSION_FLAG 
        public ActionResult GetLogFile(long versionFlagId)
        {
            versionsFlagViewModel.GetLogFile(versionFlagId);

            return View(versionsFlagViewModel);
        }
    }
}

VerzovaciSystem/VerzovaciSystem/Views/SelectionMask/SelectionMask.cshtml
@model VerzovaciSystem.Models.SelectionMaskViewModel
@{
    ViewBag.Title = "Vyhledávací maska";
}
<div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
        <h2>Vyhledávací maska</h2>
    </div>
    <div class="col-md-4">
    </div>
</div>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken();
    @Html.ValidationSummary(true);
    
    
    <div class="form-horizontal">

        <div class="form-group">
            @Html.LabelFor(model => model.SelectionMaskEntity.Id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SelectionMaskEntity.Id, new { @class = "form-control", @style = "max-width:280px" })
                @Html.ValidationMessageFor(model => model.SelectionMaskEntity.Id, "", new { @class = "text-danger" })
            </div>
        </div><br />

        <div class="form-group">
            @Html.LabelFor(model => model.SelectionMaskEntity.CompanyTyp, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SelectionMaskEntity.CompanyTyp, new SelectList(Model.CompanyTypes, "Value", "Text"),new { @class = "form-control", @style = "max-width:280px" })
                @Html.ValidationMessageFor(model => model.SelectionMaskEntity.CompanyTyp, "", new { @class = "text-danger" })
            </div>
            <br /><br />
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectionMaskEntity.Company, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SelectionMaskEntity.Company, new SelectList(Model.Companies, "Value", "Text"), new { @class = "form-control", @style = "max-width:280px" })
                @Html.ValidationMessageFor(model => model.SelectionMaskEntity.Company, "", new { @class = "text-danger" })
            </div>
            <br /><br />
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectionMaskEntity.CompanyWithGroup, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SelectionMaskEntity.CompanyWithGroup, new SelectList(Model.CompaniesWithGroups, "Value", "Text"), new { @class = "form-control", @style = "max-width:280px" })
                @Html.ValidationMessageFor(model => model.SelectionMaskEntity.CompanyWithGroup, "", new { @class = "text-danger" })
            </div>
            <br /><br />
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectionMaskEntity.Group, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SelectionMaskEntity.Group, new { @class = "form-control", @style = "max-width:280px" })
                @Html.ValidationMessageFor(model => model.SelectionMaskEntity.Group, "", new { @class = "text-danger" })
            </div>
        </div><br />

        <div class="form-group">
                @Html.LabelFor(model => model.SelectionMaskEntity.VersionDateFrom,  new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SelectionMaskEntity.VersionDateFrom, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SelectionMaskEntity.VersionDateFrom, "", new { @class = "text-danger" })
            </div>
        </div><br />

            <div class="form-group">
                @Html.LabelFor(model => model.SelectionMaskEntity.VersionDateTo, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SelectionMaskEntity.VersionDateTo, new { @class = "form-control" })
                    @*@Html.ValidationMessageFor(model => model.SelectionMaskEntity.VersionDateTo, "", new { @class = "text-danger" })*@
                </div>
            </div><br />

            <div class="form-group">
                @Html.LabelFor(model => model.SelectionMaskEntity.CreationDateFrom, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SelectionMaskEntity.CreationDateFrom, new { @class = "form-control" })
                    @*@Html.ValidationMessageFor(model => model.SelectionMaskEntity.CreationDateFrom, "", new { @class = "text-danger" })*@
                </div>
            </div><br />
            

            <div class="form-group">
                @Html.LabelFor(model => model.SelectionMaskEntity.CreationDateTo, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SelectionMaskEntity.CreationDateTo, new { @class = "form-control" })
                    @*@Html.ValidationMessageFor(model => model.SelectionMaskEntity.CreationDateTo, "", new { @class = "text-danger" })*@
                </div>
            </div><br />

        @*<div class="form-group">
            @Html.LabelFor(model => model.SelectionMaskEntity.SearchInDeleted, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.SelectionMaskEntity.SearchInDeleted, new { @class = "form-control", @style = "max-width:280px" })
                @Html.ValidationMessageFor(model => model.SelectionMaskEntity.SearchInDeleted, "", new { @class = "text-danger" })
            </div>
        </div><br />*@

            @*<div class="form-group">
                @Html.LabelFor(model => model.GlobalStatus, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.GlobalStatus, new SelectList(Model.GlobalStatusChoice, "Value", "Text"))
                    @Html.ValidationMessageFor(model => model.GlobalStatus, "", new { @class = "text-danger" })
                </div>
                <br /><br />
            </div>*@
        </div>

    <div class="form-horizontal">

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Vyhledat" class="btn btn-default" />
            </div>
        </div>

    </div>


}

@*-----------------------------------------------------------------------------------------------------*@

@*<script src="~/Scripts/MyScripts/SelectionMask.js"></script>

     <input type="text" id="cislo1" size="5" /> +
    <input type="text" id="cislo2" size="5" />
    <button id="tlacitko">Sečti</button>

    <form method="post">
        <div class="form-horizontal">

            <div class="form-group">
                @Html.LabelFor(model => model.SelectionMaskEntity.CompanyTyp, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <select name="CompanyType">
                        @foreach (var item in Model.CompanyTypes)
                        {
                            <option value="@item.Value">@item.Text</option>
                        }
                    </select>
                </div>
                <br /><br />
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SelectionMaskEntity.Company, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <select name="Company">
                        @foreach (var item in Model.Companies)
                        {
                            <option value="@item.Value">@item.Text</option>
                        }
                    </select>
                </div>
                <br /><br />
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SelectionMaskEntity.VersionDateFrom, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="datetime" id="VersionDateFrom"  value="@Model.SelectionMaskEntity.VersionDateFrom" class="form-control"/>
                </div>
                <br /><br />
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SelectionMaskEntity.VersionDateTo, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="date" id="VersionDateTo" value="@Model.SelectionMaskEntity.VersionDateTo" class="form-control" />
                </div>
                <br /><br />
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SelectionMaskEntity.CreationDateFrom, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="date" id="CreationDateFrom" value="@Model.SelectionMaskEntity.CreationDateFrom" class="form-control" />
                </div>
                <br /><br />
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SelectionMaskEntity.CreationDateTo, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="date" id="CreationDateTo" value="@Model.SelectionMaskEntity.CreationDateTo" class="form-control" />
                </div>
                <br /><br />
            </div>

        </div>

        <div class="form-horizontal">

            <div class="form-group">
                <div id="Find" class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Vyhledat" class="btn btn-default" />
                </div>
            </div>

        </div>

    </form>*@

VerzovaciSystem/VerzovaciSystem/Views/SelectionMask/SelectionMaskOutput.cshtml
@model VerzovaciSystem.Models.SelectionMaskViewModel
@{
    ViewBag.Title = "Výběr";
}

<h2>
    @if (TempData.ContainsKey("todaysVersions"))
    {
        @TempData["todaysVersions"]
    }
    @if (TempData.ContainsKey("selectionMaskVersions"))
    {
        @TempData["selectionMaskVersions"]
    }
</h2>


<table border="1">
    <thead>
        <tr>
            <th>
                @Html.LabelFor(model => model.SelectionMaskOutputEntity.Id, new { @class = "control-label col-md-2" })
            </th>
            <th>
                @Html.LabelFor(model => model.SelectionMaskOutputEntity.Company, new { @class = "control-label col-md-2" })
            </th>
            <th>
                @Html.LabelFor(model => model.SelectionMaskOutputEntity.Group, new { @class = "control-label col-md-2" })
            </th>
            <th>
                @Html.LabelFor(model => model.SelectionMaskOutputEntity.Date, new { @class = "control-label col-md-2" })
            </th>
            <th>
                @Html.LabelFor(model => model.SelectionMaskOutputEntity.Created, new { @class = "control-label col-md-2" })
            </th>
            <th>
                @Html.LabelFor(model => model.SelectionMaskOutputEntity.User, new { @class = "control-label col-md-2" })
            </th>
            <th>
                @Html.LabelFor(model => model.SelectionMaskOutputEntity.Status, new { @class = "control-label col-md-2" })
            </th>
            <th>
                @Html.LabelFor(model => model.SelectionMaskOutputEntity.CompanyType, new {@class = "control-label col-md-2" })
            </th>
            <th>
                Odkaz na události verze
            </th>
            <th>
                Odkaz na detail verze
            </th>
        </tr>
    </thead>
    
    @foreach (var item in Model.SelectionResult)
    {
        <tbody>
            <tr>
                <td>
                    @item.Id
                </td>
                <td>
                    @item.Company
                </td>
                <td>
                    @item.Group
                </td>
                <td>
                    @item.Date
                </td>
                <td>
                    @item.Created
                </td>
                <td>
                    @item.User
                </td>
                <td>
                    @item.Status
                </td>
                <td>
                    @item.CompanyType
                </td>
                <td>
                    @Html.ActionLink("Události", "GetFlagVersions", "VersionsFlag",new { versionLogId=item.Id },null)
                </td>
                <td>
                    @Html.ActionLink("Detail","GetVersion", "Versions",new { idVersion=item.Id},null)
                </td>
            </tr>
        </tbody>
    }

</table>